### ISSUE TITLE
can't load "ttrc"

### ISSUE THREAD

**Issue by AleksandrTim** [joshuaulrich/TTR#19]
Hi, Joshua!
Please, see below:

library(TTR)
data(ttrc)

 Error in force(Symbols) : object 'ttrc' not found 

What's wrong?

**Comment by joshuaulrich** [comment]
I cannot replicate this.  Is it possible that your TTR installation is corrupt? What's your `sessionInfo()` output?

**Comment by AleksandrTim** [comment]
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-5 xts_0.9-7      zoo_1.7-12     TTR_0.23-0    

loaded via a namespace (and not attached):
[1] tools_3.2.2     grid_3.2.2      lattice_0.20-33

**Comment by joshuaulrich** [comment]
Did you try reinstalling TTR? What GUI are you using?

**Comment by AleksandrTim** [comment]
Yep, I tried. RStudio-0.99.486

**Comment by joshuaulrich** [comment]
Does it work from the regular R Windows GUI?  If so, then it's an issue with RStudio and I can't fix it.

**Comment by AleksandrTim** [comment]
No... It doesn't work from R Windows GUI. on my PC. Curiously...
I updated R to version 3.2.3...
It doesn't work

**Comment by joshuaulrich** [comment]
I can't replicate this and I don't think it's related to TTR... but here are a couple more things you can try in order to find the source of the error:

1. Do you have this issue with data sets from other packages? For example: `library(xts); data(sample_matrix)`.
2. Maybe the mirror you're using has a corrupt Windows binary for TTR? Do you have the issue if you install TTR from a different mirror?
