### ISSUE TITLE
Problems installing TTR on RStudio

### ISSUE THREAD

**Issue by devtl** [joshuaulrich/TTR#61]
Hey Joshua,

Im having issues trying to install your package. The installation process keeps throwing up an error,
```
make: gfortran-4.8: No such file or directory
make: *** [movingAverages.o] Error 1
ERROR: compilation failed for package ‘TTR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/TTR’
```
 and then exiting with a non-zero exit status.

I've tried installing from CRAN, gitHub, and even downloading tar.gz. All same error and exit status.

```
sessionInfo()

R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.13.2

> .libPaths()
"/Library/Frameworks/R.framework/Versions/3.3/Resources/library"
```

**Comment by joshuaulrich** [comment]
Before getting to your problem, I want you to know that I'm closing this because there's nothing I can change in the TTR package to fix your problem.  I use this tracker to organize bugs and features, not as a support forum.  So, no hard feelings... I'm simply trying to stay organized.

Your problem is specific to macOS. There's been some sort of issue with macOS binaries for R-3.3.x on CRAN, which is why you can't install that way.  The error you provided is because you do not have a Fortran compiler installed.  Getting a suitable compiler is [documented on CRAN](https://cran.r-project.org/bin/macosx/).

You might find success by upgrading to R-3.4.x.  Though I'm not sure if those macOS binaries are available.
